window.__fire=function(b){const r=b.getBoundingClientRect(),cx=r.x+r.width/2,cy=r.y+r.height/2;for(const t of ['pointerover','pointerenter','mouseover','pointermove','mousemove','pointerdown','mousedown','pointerup','mouseup','click'])b.dispatchEvent(new MouseEvent(t,{bubbles:true,cancelable:true,composed:true,clientX:cx,clientY:cy,button:0,buttons:t.includes('down')?1:0}));};
window.__pillEl=()=>[...document.querySelectorAll('button')].find(x=>/모드 선택 도구/.test(x.getAttribute('aria-label')||''));
window.__setPro=async()=>{const w=ms=>new Promise(r=>setTimeout(r,ms));let p=window.__pillEl();if(!p)return 'no pill';
 if(!/Pro/.test(p.innerText)){window.__fire(p);await w(900);const it=[...document.querySelectorAll('gem-menu-item,[role="menuitem"]')].find(x=>/^3\.1 Pro/.test((x.innerText||'').trim()));if(it)window.__fire(it);await w(900);}
 p=window.__pillEl(); if(!/Extended|최고가/.test(p.innerText)){window.__fire(p);await w(900);const it=[...document.querySelectorAll('gem-menu-item,[role="menuitem"]')].find(x=>/^확장된 사고 모델|^최고가/.test((x.innerText||'').trim()));if(it)window.__fire(it);await w(900);}
 return window.__pillEl().innerText.replace(/\n/g,' ');};
window.__openUpload=()=>{const b=[...document.querySelectorAll('button,[role="button"]')].find(x=>(x.getAttribute('aria-label')||'').trim()==='업로드 및 도구');window.__fire(b);return !!b;};
window.__expose=()=>{const f=[...document.querySelectorAll('input[type=file]')];const i=f.find(x=>(x.accept||'')==='image/*');if(i){document.body.appendChild(i);i.id='__imgup';i.setAttribute('aria-label','내가 노출시킨 이미지 업로드 입력');i.style.cssText='position:fixed;left:12px;top:12px;width:240px;height:48px;opacity:1;z-index:2147483647;display:block;visibility:visible';}return {n:f.length,moved:!!i};};
window.__attach=()=>({thumbs:[...document.querySelectorAll('img')].filter(i=>/^blob:/.test(i.src)).map(i=>i.naturalWidth), close:[...document.querySelectorAll('button')].filter(b=>/첨부파일 닫기|파일 삭제/.test(b.getAttribute('aria-label')||'')).length});
window.__rechange=async()=>{const i=document.getElementById('__imgup');i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,4000));return window.__attach();};
window.__ready=async()=>{let a=window.__attach(); if(!a.thumbs.length){a=await window.__rechange();} if(!a.thumbs.length){await new Promise(r=>setTimeout(r,6000)); a=await window.__rechange();} const i=document.getElementById('__imgup'); if(i)i.style.display='none'; const ed=document.querySelector('div[contenteditable="true"]'); ed.focus(); return a;};
window.__sent=()=>{const sb=[...document.querySelectorAll('button')].find(x=>/메시지 보내기/.test(x.getAttribute('aria-label')||'')); const busy=[...document.querySelectorAll('button')].filter(x=>/중지/.test(x.getAttribute('aria-label')||'')).length; return {sb:!!sb,busy,href:location.href.slice(-24),vis:document.visibilityState,turns:document.querySelectorAll('user-query').length,imgs:[...document.querySelectorAll('model-response img')].filter(i=>/^blob:/.test(i.src)&&i.naturalWidth>400).length};};
window.__grab1=(pid)=>{const imgs=[...document.querySelectorAll('img')].filter(i=>/^blob:/.test(i.src)&&i.naturalWidth>400&&i.closest('model-response'));const stop=[...document.querySelectorAll('button')].filter(x=>/중지|Stop/.test(x.getAttribute('aria-label')||'')).length;let name=null;if(imgs.length>=1&&!stop){const L=imgs[imgs.length-1];name=pid+'_'+Date.now()+'.png';const a=document.createElement('a');a.href=L.src;a.download=name;document.body.appendChild(a);a.click();a.remove();}return {n:imgs.length,stop,name};};
'ok'
